[connections.snowflake]
account = "<ACCOUNT-IDENTIFIER>" # Write your [Account identifier]
user = "streamlit_app_user" # or your Snowflake username
password = "<PASSWORD>" # Your Snowflake [Password]
role = "movie_app_role" # or your role
warehouse = "COMPUTE_WH"# or your warehouse name
database = "IMDB_ANALYTICS"# or your database name
schema = "PUBLIC"# or your schema name
